#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

echo fail && exit 1

PACKAGE="target/website.zip"

cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
hugo
echo "Packaging as $PACKAGE"
mkdir -p "$(dirname $PACKAGE)"
(
    cd public
    cp ../Staticfile .
    zip -qr "../$PACKAGE" .
)
