version: '3'
services:
  app:
    image: eu.gcr.io/halfpipe-io/hugo
    working_dir: /home/dev/code
    volumes:
    - .:/home/dev/code
    command: hugo serve --buildDrafts --bind 0.0.0.0
    ports:
    - "1313:1313"
